In [1]:
import pandas as pd

df = pd.read_csv('modelCF.csv')

df

  customer     item
0        A     Susu
1        A     Roti
2        B  Mentega
3        C    Meses
4        D     Susu
5        D  Mentega
6        D     Roti
7        E     Roti
8        E  Mentega

In [2]:
basket = (#assign -- nilai 1
    df.assign(value=1).pivot_table(
        index="customer",
        columns="item",
        values="value",
        fill_value=0  # mengisi yang tidak berpasangan dengan nilai 0
    )
)

basket

item      Mentega  Meses  Roti  Susu
customer
A             0.0    0.0   1.0   1.0
B             1.0    0.0   0.0   0.0
C             0.0    1.0   0.0   0.0
D             1.0    0.0   1.0   1.0
E             1.0    0.0   1.0   0.0