In [2]:
import pandas as pd

df = pd.read_csv('modelCF.csv')

df

  customer     item
0        A     Susu
1        A     Roti
2        B  Mentega
3        C    Meses
4        D     Susu
5        D  Mentega
6        D     Roti
7        E     Roti
8        E  Mentega

In [3]:
basket = (#assign -- nilai 1
    df.assign(value=1).pivot_table(
        index="customer",
        columns="item",
        values="value",
        fill_value=0  # mengisi yang tidak berpasangan dengan nilai 0
    )
)

basket

item      Mentega  Meses  Roti  Susu
customer
A             0.0    0.0   1.0   1.0
B             1.0    0.0   0.0   0.0
C             0.0    1.0   0.0   0.0
D             1.0    0.0   1.0   1.0
E             1.0    0.0   1.0   0.0

In [4]:
# frequent itemset -- support
from mlxtend.frequent_patterns import apriori, association_rules

freq_item = apriori(
    basket.astype(bool),
    min_support=0.2,
    use_colnames=True
)

print(freq_item)

ModuleNotFoundError: No module named 'mlxtend'

In [ ]:
rules = association_rules(
    freq_item,
    metric="confidence",
    min_threshold=0.3
)

print(rules)

#### Matrix Factorization

In [ ]:
matrix = df1.pivot(index="user", columns="movie", values="rating")
matrix

In [ ]:
from sklearn.decomposition import NMF

# factorization
nmf = NMF(n_components=2, random_state=42)

In [ ]:
# matrix user
W = nmf.fit_transform(matrix.values)

# matrix movie
H = nmf.components_

In [ ]:
W

In [ ]:
H

In [ ]:
# Rating prediction
R_pred = W @ H
R_pred