###

### CF and KNN, Neighborhood Formation

#### Importing the Libraries

In [1]:
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity as sim

#### Load the Dataset

In [2]:
df = pd.read_csv('/code/github/Kapita-Selekta/01_ks_11_9.ipynb/cf_data_matrix.csv')

df.head()

  user item  rating
0   U1   I1     4.0
1   U2   I1     1.0
2   U3   I1     4.0
3   U4   I1     5.0
4   U5   I1     4.0

#### Rate and Fill the Nan Value

In [3]:
rating_matrix = df.pivot(index='user', columns="item", values="rating").fillna(0)

rating_matrix

item   I1  I10  I11  I12   I2   I3   I4   I5   I6   I7   I8   I9
user
U1    4.0  0.0  0.0  2.0  1.0  0.0  3.0  3.0  4.0  5.0  3.0  5.0
U10   1.0  0.0  5.0  1.0  2.0  0.0  5.0  0.0  1.0  4.0  0.0  5.0
U2    1.0  4.0  3.0  2.0  4.0  5.0  5.0  0.0  1.0  0.0  3.0  4.0
U3    4.0  3.0  3.0  4.0  3.0  5.0  3.0  1.0  3.0  5.0  5.0  3.0
U4    5.0  4.0  1.0  5.0  2.0  2.0  1.0  2.0  4.0  5.0  0.0  4.0
U5    4.0  1.0  0.0  0.0  0.0  4.0  0.0  5.0  1.0  4.0  2.0  1.0
U6    3.0  3.0  5.0  3.0  5.0  0.0  3.0  1.0  4.0  0.0  5.0  0.0
U7    1.0  4.0  5.0  4.0  1.0  3.0  5.0  3.0  2.0  3.0  5.0  1.0
U8    5.0  0.0  4.0  3.0  4.0  0.0  1.0  3.0  2.0  0.0  5.0  1.0
U9    2.0  5.0  5.0  0.0  2.0  5.0  0.0  1.0  2.0  2.0  3.0  0.0

#### Compute

In [4]:
user_sim = sim(rating_matrix)

user_sim

array([[1.        , 0.68118807, 0.50876697, 0.78000239, 0.81618285,
        0.69110895, 0.5463696 , 0.63099803, 0.63678479, 0.37277509],
       [0.68118807, 1.        , 0.65847538, 0.65079365, 0.58686146,
        0.29364007, 0.53571429, 0.64653345, 0.4709505 , 0.41210713],
       [0.50876697, 0.65847538, 1.        , 0.8180134 , 0.59559429,
        0.39476596, 0.72020745, 0.80057095, 0.57158459, 0.72970012],
       [0.78000239, 0.65079365, 0.8180134 , 1.        , 0.83905846,
        0.70272837, 0.76388889, 0.87338729, 0.73258967, 0.7895928 ],
       [0.81618285, 0.58686146, 0.59559429, 0.83905846, 1.        ,
        0.66864063, 0.58901904, 0.66193903, 0.58917612, 0.58658117],
       [0.69110895, 0.29364007, 0.39476596, 0.70272837, 0.66864063,
        1.        , 0.335992  , 0.56493268, 0.52124669, 0.60074212],
       [0.5463696 , 0.53571429, 0.72020745, 0.76388889, 0.58901904,
        0.335992  , 1.        , 0.8039133 , 0.88425863, 0.70359754],
       [0.63099803, 0.64653345, 0.80057095, 0.87338729, 0.66193903,
        0.56493268, 0.8039133 , 1.        , 0.69527472, 0.77093468],
       [0.63678479, 0.4709505 , 0.57158459, 0.73258967, 0.58917612,
        0.52124669, 0.88425863, 0.69527472, 1.        , 0.57987933],
       [0.37277509, 0.41210713, 0.72970012, 0.7895928 , 0.58658117,
        0.60074212, 0.70359754, 0.77093468, 0.57987933, 1.        ]])

In [5]:
df_user_sim = pd.DataFrame(user_sim, index=rating_matrix.index, columns=rating_matrix.index)

df_user_sim

user,U1,U10,U2,U3,U4,U5,U6,U7,U8,U9
user,,,,,,,,,,
U1,1.000000,0.681188,0.508767,0.780002,0.816183,0.691109,0.546370,0.630998,0.636785,0.372775
U10,0.681188,1.000000,0.658475,0.650794,0.586861,0.293640,0.535714,0.646533,0.470951,0.412107
U2,0.508767,0.658475,1.000000,0.818013,0.595594,0.394766,0.720207,0.800571,0.571585,0.729700
U3,0.780002,0.650794,0.818013,1.000000,0.839058,0.702728,0.763889,0.873387,0.732590,0.789593
U4,0.816183,0.586861,0.595594,0.839058,1.000000,0.668641,0.589019,0.661939,0.589176,0.586581
U5,0.691109,0.293640,0.394766,0.702728,0.668641,1.000000,0.335992,0.564933,0.521247,0.600742
U6,0.546370,0.535714,0.720207,0.763889,0.589019,0.335992,1.000000,0.803913,0.884259,0.703598
U7,0.630998,0.646533,0.800571,0.873387,0.661939,0.564933,0.803913,1.000000,0.695275,0.770935
U8,0.636785,0.470951,0.571585,0.732590,0.589176,0.521247,0.884259,0.695275,1.000000,0.579879
U9,0.372775,0.412107,0.729700,0.789593,0.586581,0.600742,0.703598,0.770935,0.579879,1.000000

In [6]:
kandidate = df_user_sim['U1'].sort_values(ascending=False)

kandidate

user
U1     1.000000
U4     0.816183
U3     0.780002
U5     0.691109
U10    0.681188
U8     0.636785
U7     0.630998
U6     0.546370
U2     0.508767
U9     0.372775
Name: U1, dtype: float64

In [7]:
kandidate.head(7)

user
U1     1.000000
U4     0.816183
U3     0.780002
U5     0.691109
U10    0.681188
U8     0.636785
U7     0.630998
Name: U1, dtype: float64

In [8]:
# nearest = 7
k_nb = kandidate.index.to_list()[1:8]

k_nb

['U4', 'U3', 'U5', 'U10', 'U8', 'U7', 'U6']

#### Item-Based

In [9]:
item_sim = sim(rating_matrix.T)

item_sim

array([[1.        , 0.61516867, 0.60456354, 0.81751912, 0.75393703,
        0.58777469, 0.53267081, 0.8413383 , 0.90509711, 0.7865834 ,
        0.76920089, 0.6858703 ],
       [0.61516867, 1.        , 0.76270769, 0.7394006 , 0.72269123,
        0.85875386, 0.63384214, 0.48863276, 0.73720978, 0.58055758,
        0.71961056, 0.49465225],
       [0.60456354, 0.76270769, 1.        , 0.70429521, 0.8564029 ,
        0.60764362, 0.7933125 , 0.47060485, 0.69986771, 0.51068823,
        0.81964155, 0.52374658],
       [0.81751912, 0.7394006 , 0.70429521, 1.        , 0.79291881,
        0.55634864, 0.74893086, 0.62501009, 0.88724426, 0.70717693,
        0.78169721, 0.69773116],
       [0.75393703, 0.72269123, 0.8564029 , 0.79291881, 1.        ,
        0.57008771, 0.74549932, 0.46577801, 0.80374557, 0.45927933,
        0.84007452, 0.61117693],
       [0.58777469, 0.85875386, 0.60764362, 0.55634864, 0.57008771,
        1.        , 0.54807692, 0.54894114, 0.5547002 , 0.62660051,
        0.66825511, 0.50569587],
       [0.53267081, 0.63384214, 0.7933125 , 0.74893086, 0.74549932,
        0.54807692, 1.        , 0.44681256, 0.68181899, 0.62660051,
        0.71965934, 0.79899948],
       [0.8413383 , 0.48863276, 0.47060485, 0.62501009, 0.46577801,
        0.54894114, 0.44681256, 1.        , 0.70577387, 0.7249586 ,
        0.70522879, 0.49683455],
       [0.90509711, 0.73720978, 0.69986771, 0.88724426, 0.80374557,
        0.5547002 , 0.68181899, 0.70577387, 1.        , 0.78535496,
        0.80314268, 0.71716954],
       [0.7865834 , 0.58055758, 0.51068823, 0.70717693, 0.45927933,
        0.62660051, 0.62660051, 0.7249586 , 0.78535496, 1.        ,
        0.55032953, 0.81915239],
       [0.76920089, 0.71961056, 0.81964155, 0.78169721, 0.84007452,
        0.66825511, 0.71965934, 0.70522879, 0.80314268, 0.55032953,
        1.        , 0.48662474],
       [0.6858703 , 0.49465225, 0.52374658, 0.69773116, 0.61117693,
        0.50569587, 0.79899948, 0.49683455, 0.71716954, 0.81915239,
        0.48662474, 1.        ]])

In [10]:
df_item_sim = pd.DataFrame(item_sim, index = rating_matrix.T.index,columns = rating_matrix.T.index)

df_item_sim

item,I1,I10,I11,I12,I2,I3,I4,I5,I6,I7,I8,I9
item,,,,,,,,,,,,
I1,1.000000,0.615169,0.604564,0.817519,0.753937,0.587775,0.532671,0.841338,0.905097,0.786583,0.769201,0.685870
I10,0.615169,1.000000,0.762708,0.739401,0.722691,0.858754,0.633842,0.488633,0.737210,0.580558,0.719611,0.494652
I11,0.604564,0.762708,1.000000,0.704295,0.856403,0.607644,0.793313,0.470605,0.699868,0.510688,0.819642,0.523747
I12,0.817519,0.739401,0.704295,1.000000,0.792919,0.556349,0.748931,0.625010,0.887244,0.707177,0.781697,0.697731
I2,0.753937,0.722691,0.856403,0.792919,1.000000,0.570088,0.745499,0.465778,0.803746,0.459279,0.840075,0.611177
I3,0.587775,0.858754,0.607644,0.556349,0.570088,1.000000,0.548077,0.548941,0.554700,0.626601,0.668255,0.505696
I4,0.532671,0.633842,0.793313,0.748931,0.745499,0.548077,1.000000,0.446813,0.681819,0.626601,0.719659,0.798999
I5,0.841338,0.488633,0.470605,0.625010,0.465778,0.548941,0.446813,1.000000,0.705774,0.724959,0.705229,0.496835
I6,0.905097,0.737210,0.699868,0.887244,0.803746,0.554700,0.681819,0.705774,1.000000,0.785355,0.803143,0.717170
I7,0.786583,0.580558,0.510688,0.707177,0.459279,0.626601,0.626601,0.724959,0.785355,1.000000,0.550330,0.819152
I8,0.769201,0.719611,0.819642,0.781697,0.840075,0.668255,0.719659,0.705229,0.803143,0.550330,1.000000,0.486625
I9,0.685870,0.494652,0.523747,0.697731,0.611177,0.505696,0.798999,0.496835,0.717170,0.819152,0.486625,1.000000

In [11]:
kandidate = df_item_sim['I1'].sort_values(ascending=False)

kandidate

item
I1     1.000000
I6     0.905097
I5     0.841338
I12    0.817519
I7     0.786583
I8     0.769201
I2     0.753937
I9     0.685870
I10    0.615169
I11    0.604564
I3     0.587775
I4     0.532671
Name: I1, dtype: float64

In [12]:
# nearest = 7
k_nb = kandidate.index.to_list()[1:8]

k_nb

['I6', 'I5', 'I12', 'I7', 'I8', 'I2', 'I9']